export enum AppStatus {
  IDLE = 'IDLE',
  REQUESTING_PERMISSION = 'REQUESTING_PERMISSION',
  READY_TO_RECORD = 'READY_TO_RECORD',
  RECORDING = 'RECORDING',
  RECORDED = 'RECORDED',
  PROCESSING = 'PROCESSING',
  AWAITING_FEEDBACK = 'AWAITING_FEEDBACK',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}
